User tinyproxy
Group tinyproxy
Port PROXY_PORT
Listen 127.0.0.1
Bind PUBLIC_IP
Timeout 600
DefaultErrorFile "/usr/share/tinyproxy/default.html"
LogFile "/var/log/tinyproxy/egress-INSTANCE.log"
LogLevel Info
PidFile "/run/tinyproxy/tinyproxy-INSTANCE.pid"
MaxClients 100
Allow 127.0.0.1
Allow ::1
ViaProxyName "tinyproxy"
